name: CI

on:
  push:
    branches: [ "PHPUnit_9" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [ "PHPUnit_9" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
